on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: number
      deploy-env:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.deploy-env }}
    env:
      DEFAULT_ENVIRONMENT: ${{ vars.DEFAULT_ENVIRONMENT }}
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java-version }}
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash
    - name: Build with Gradle
      run: ./gradlew ${{ inputs.target }}
      shell: bash
